mod support;

use tempfile::tempdir;

fn strip(dir: &tempfile::TempDir, extra: &[&str]) -> std::process::Output {
    let root = dir.path().display().to_string();
    let mut args = vec!["--root", root.as_str(), "strip-comments"];
    args.extend_from_slice(extra);
    let out = support::run(&args).output().expect("output");
    assert!(
        out.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    out
}

#[test]
fn dry_run_previews_without_writing() {
    let dir = tempdir().expect("tempdir");
    support::write_file(dir.path(), "src/a.ts", "// gone\nexport const a = 1;\n");

    let out = strip(&dir, &["--dry-run"]);
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(text.contains("DRY RUN"), "preview: {text}");
    assert_eq!(
        support::read_file(dir.path(), "src/a.ts"),
        "// gone\nexport const a = 1;\n",
        "dry run must not write"
    );
}

#[test]
fn apply_strips_comments_from_the_selected_language_only() {
    let dir = tempdir().expect("tempdir");
    support::write_file(dir.path(), "src/a.ts", "// gone\nexport const a = 1;\n");
    support::write_file(dir.path(), "src/b.sql", "-- gone\nSELECT 1;\n");

    strip(&dir, &["--lang", "sql"]);

    assert_eq!(
        support::read_file(dir.path(), "src/a.ts"),
        "// gone\nexport const a = 1;\n",
        "a .ts file is out of scope for --lang sql"
    );
    assert_eq!(support::read_file(dir.path(), "src/b.sql"), "SELECT 1;\n");
}

#[test]
fn functional_directives_survive_until_asked_otherwise() {
    let dir = tempdir().expect("tempdir");
    let source = "//go:build linux\n// a note\npackage main\n";
    support::write_file(dir.path(), "main.go", source);

    strip(&dir, &["--lang", "go"]);

    let kept = support::read_file(dir.path(), "main.go");
    assert!(kept.contains("//go:build linux"), "directive kept: {kept}");
    assert!(!kept.contains("a note"), "comment removed: {kept}");

    let dir2 = tempdir().expect("tempdir");
    support::write_file(dir2.path(), "main.go", source);
    strip(&dir2, &["--lang", "go", "--strip-directives"]);
    assert_eq!(
        support::read_file(dir2.path(), "main.go"),
        "package main\n",
        "--strip-directives removes the build constraint too"
    );
}

#[test]
fn a_migration_runner_marker_is_not_treated_as_commentary() {
    // The runner splits a migration on this marker, so losing it would fold the
    // rollback into the forward pass.
    let dir = tempdir().expect("tempdir");
    support::write_file(
        dir.path(),
        "001_init.sql",
        "-- a note\nCREATE TABLE t (id INT);\n-- +migrate down\nDROP TABLE t;\n",
    );

    strip(&dir, &["--lang", "sql"]);

    assert_eq!(
        support::read_file(dir.path(), "001_init.sql"),
        "CREATE TABLE t (id INT);\n-- +migrate down\nDROP TABLE t;\n"
    );
}

#[test]
fn graphql_descriptions_are_kept_but_comments_go() {
    let dir = tempdir().expect("tempdir");
    support::write_file(
        dir.path(),
        "schema.graphqls",
        "# a note\n\"\"\"\nWhat this type is for.\n\"\"\"\ntype Post {\n  id: ID!\n}\n",
    );

    strip(&dir, &["--lang", "graphql"]);

    let got = support::read_file(dir.path(), "schema.graphqls");
    assert!(!got.contains("a note"), "comment removed: {got}");
    assert!(
        got.contains("What this type is for."),
        "description is schema, not commentary: {got}"
    );
}

#[test]
fn a_generated_file_is_skipped_unless_generated_is_passed() {
    let dir = tempdir().expect("tempdir");
    let source = "// Code generated by tool. DO NOT EDIT.\n// a note\nexport const a = 1;\n";
    support::write_file(dir.path(), "gen.ts", source);

    strip(&dir, &["--lang", "ts"]);
    assert_eq!(
        support::read_file(dir.path(), "gen.ts"),
        source,
        "generated file left alone"
    );

    strip(&dir, &["--lang", "ts", "--generated"]);
    assert!(!support::read_file(dir.path(), "gen.ts").contains("a note"));
}

#[test]
fn string_contents_that_look_like_comments_are_left_alone() {
    let dir = tempdir().expect("tempdir");
    support::write_file(
        dir.path(),
        "a.ts",
        "const url = 'https://example.com';\nconst re = /^https?:\\/\\//;\n// gone\n",
    );

    strip(&dir, &["--lang", "ts"]);

    let got = support::read_file(dir.path(), "a.ts");
    assert!(got.contains("'https://example.com'"), "string kept: {got}");
    assert!(got.contains("/^https?:\\/\\//"), "regex kept: {got}");
    assert!(!got.contains("gone"), "comment removed: {got}");
}

#[test]
fn running_twice_reports_nothing_left_to_do() {
    let dir = tempdir().expect("tempdir");
    support::write_file(dir.path(), "a.sql", "-- one\n-- two\nSELECT 1;\n");

    strip(&dir, &["--lang", "sql"]);
    let after_first = support::read_file(dir.path(), "a.sql");

    let out = strip(&dir, &["--lang", "sql"]);
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(
        text.contains("No comments found"),
        "second pass is a no-op: {text}"
    );
    assert_eq!(
        support::read_file(dir.path(), "a.sql"),
        after_first,
        "a second pass must not change the file again"
    );
}
